version: "3"
services:
  # backend:
  #     container_name: nest
  #     build:
  #       context: ./
  #       dockerfile: Dockerfile
  #     working_dir: /var/www/backend
  #     volumes:
  #       - .:/var/www/backend
  #     depends_on:
  #       - postgres
  #     env_file: 
  #       - .env    
  #     environment:
  #       - POSTGRES_PORT:${POSTGRES_PORT}
  #       - POSTGRES_DB:${POSTGRES_DB}
  #       - POSTGRES_USER:${POSTGRES_USER}
  #       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     ports:
  #       - "9000:3000"
  #     networks:
  #       - postgres

  postgres:
    container_name: postgres
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file: 
      - .env
    environment:
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - postgres
 
  # pgadmin:
  #   links:
  #     - postgres:postgres
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   ports:
  #   - "8080:80"
  #   volumes:
  #     - /data/pgadmin:/root/.pgadmin
  #   networks:
  #     - postgres
      
networks:
  postgres:
    driver: bridge